### ISSUE TITLE
[bug fix request] second heavy firing speed upgrade in mvm

### ISSUE THREAD

**Issue by vlad55523** [mastercomfig/team-comtress-2#86]
the upgrade does nothing, it works like the 10% firing speed upgrade, but the third upgrade works well surprisingly

**Comment by mastercoms** [comment]
This was already fixed.

**Comment by Yttrium-tYcLief** [comment]
This is sort of irrelevant but for those curious, here's some fun numbers on the math *prior* to the fix:

> Heavy Stock Minigun:
> 0 firing speed: 124 DPS (100% total; this should be 100%)
> 1 firing speed: 144 DPS (116% total; this should be 110%)
> 2 firing speed: 144 DPS (116% total; this should be 120%)
> 3 firing speed: 172 DPS (139% total; this should be 130%)
> 4 firing speed: 208 DPS (168% total; this should be 140%)
> 
> Brass Beast (quoted as "20% damage bonus"):
> 0 firing speed: 142 DPS (100% total) (16% over stock)
> 1 firing speed: 166 DPS (117% total) (15% over stock)
> 2 firing speed: 166 DPS (117% total) (15% over stock)
> 3 firing speed: 200 DPS (141% total) (16% over stock)
> 4 firing speed: 240 DPS (169% total) (15% over stock)w
> 
> Tomislav (quoted as "20% firing speed penalty"):
> 0 firing speed: 104 DPS (100% total) (16% below stock)
> 1 firing speed: 108 DPS (104% total) (25% below stock)
> 2 firing speed: 124 DPS (119% total) (14% below stock)
> 3 firing speed: 144 DPS (138% total) (16% below stock)
> 4 firing speed: 172 DPS (165% total) (17% below stock)
> 
> Huo Long (quoted as "10% damage penalty"):
> 0 firing speed: 104 DPS (100% total) (16% below stock)
> 1 firing speed: 122 DPS (117% total) (15% below stock)
> 2 firing speed: 122 DPS (117% total) (15% below stock)
> 3 firing speed: 147 DPS (141% total) (15% below stock)
> 4 firing speed: 182 DPS (175% total) (12% below stock)
> 
> Natascha (quoted as "25% damage penalty"):
> 0 firing speed:  85 DPS (100% total) (31% below stock)
> 1 firing speed: 100 DPS (118% total) (31% below stock)
> 2 firing speed: 100 DPS (118% total) (31% below stock)
> 3 firing speed: 120 DPS (141% total) (30% below stock)
> 4 firing speed: 150 DPS (176% total) (28% below stock)

DPS numbers are from firing at a tank, point blank. Since tanks have 75% minigun resistance, multiply these DPS values by 4 for real damage. The scaling still shows, though.

Prior to the fix, due to rounding errors, firing speed 2 did nothing on *most* miniguns. However, on the Tomislav, it was actually firing speed *1* that did nothing, and 2 actually worked. Fun stuff!
